### ISSUE TITLE
wpt run chrome does not use the correct default OSX binary location when getting version string

### ISSUE THREAD

**Issue by kereliuk** [w3c/web-platform-tests#10992]
**What happens**

Fails out before launching the browser when I try to run wpt run on my mac.

**How to reproduce**

`./wpt run chrome infrastructure/testdriver/click.html  --log-mach-level=debug`
> Traceback (most recent call last):
  File "./wpt", line 5, in <module>
    wpt.main()
  File "/Users/jonathonkereliuk/0101/web-platform-tests/tools/wpt/wpt.py", line 132, in main
    rv = script(*args, **kwargs)
  File "/Users/jonathonkereliuk/0101/web-platform-tests/tools/wpt/run.py", line 437, in run
    **kwargs)
  File "/Users/jonathonkereliuk/0101/web-platform-tests/tools/wpt/run.py", line 424, in setup_wptrunner
    kwargs['browser_version'] = setup_cls.browser.version(kwargs.get("binary"))
  File "/Users/jonathonkereliuk/0101/web-platform-tests/tools/wpt/browser.py", line 342, in version
    version_string = call(binary, "--version").strip()
  File "/Users/jonathonkereliuk/0101/web-platform-tests/tools/wpt/utils.py", line 44, in call
    return subprocess.check_output(args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

It thinks that the binary should be at usr/bin/google-chrome.

I think this is low priority since the work around is explicitly specifying the binary location with --binary.

I believe this was introduced by #10935

**Comment by Hexcles** [comment]
Oops.

So first things first: the method should return `None` instead of raising an exception when not able to find the browser binary (or fail for whatever reasons).

Secondly, the default paths... It looks like I'd need to pretty much reimplement this [C++ class from Chromedriver](https://cs.chromium.org/chromium/src/chrome/test/chromedriver/chrome/chrome_finder.cc) in WPT in Python...
