### ISSUE TITLE
Run serve.py and then got openssl error

### ISSUE THREAD

**Issue by shihweihung** [w3c/web-platform-tests#1537]
Can someone tell how to solve this issue? I follow readme to execute.
# 

```
D:\web-platform-tests>python serve.py
DEBUG:web-platform-tests:Going to use port 52263
DEBUG:web-platform-tests:Going to use port 52264
INFO:web-platform-tests:Generating new CA in D:\web-platform-tests_certs
DEBUG:web-platform-tests:Generating a 2048 bit RSA private key
...............................................................................
.......................+++
...............................................................................
.....................+++
## writing new private key to 'D:\web-platform-tests_certs\cakey.pem'

DEBUG:web-platform-tests:Using configuration from D:\web-platform-tests_certs\
penssl.cfg
I am unable to access the D:web-platform-tests_certs directory
D:web-platform-tests_certs: No such file or directory

Traceback (most recent call last):
  File "serve.py", line 459, in <module>
    main()
  File "serve.py", line 448, in main
    config_, servers = start(config, ssl_env, **kwargs)
  File "serve.py", line 344, in start
    ssl_config = get_ssl_config(config, external_config["domains"].values(), ss
_environment)
  File "serve.py", line 327, in get_ssl_config
    key_path, cert_path = ssl_environment.host_cert_path(external_domains)
  File "D:\web-platform-tests\tools\sslutils\openssl.py", line 335, in host_cer
_path
    key, cert = self._generate_host_cert(hosts)
  File "D:\web-platform-tests\tools\sslutils\openssl.py", line 355, in _generat
_host_cert
    self._generate_ca()
  File "D:\web-platform-tests\tools\sslutils\openssl.py", line 316, in _generat
_ca
    "-out", cert_path)
  File "D:\web-platform-tests\tools\sslutils\openssl.py", line 61, in __call__
    output=stdout)
subprocess.CalledProcessError: Command '[u'openssl', 'ca', '-config', u'D:\web
platform-tests\_certs\openssl.cfg', '-batch', '-create_serial', '-keyfile', u
D:\web-platform-tests\_certs\cakey.pem', '-passin', 'pass:web-platform-tests
, '-selfsign', '-extensions', 'v3_ca', '-in', u'D:\web-platform-tests\_certs\
careq.pem', '-out', u'D:\web-platform-tests\_certs\cacert.pem']' returned no
-zero exit status 1
```

**Comment by hallvors** [comment]
I hacked around this error by doing 

    if '\\' in root_dir:
        root_dir = root_dir.replace('\\', '/')

inside get_config() in tools/sslutils/openssl.py

I have no idea if that's a proper fix though..

**Comment by gsnedders** [comment]
Sounds like somewhere we're using `/` instead of `os.sep`.

**Comment by jgraham** [comment]
Is this still broken? I made some Windows fixes over the summer that might well solve this issue.

**Comment by gsnedders** [comment]
WFM, at least. But I was using PowerShell, should check in `cmd.exe` too, which I think is pickier about separators, given that might affect `subprocess`. Will look later.

**Comment by bobholt** [comment]
@gsnedders: Did you get a chance to check this out. Something's suspect with my Windows, otherwise I'd verify it.

**Comment by foolip** [comment]
Given the WFM in https://github.com/w3c/web-platform-tests/issues/1537#issuecomment-248366389 I'll close this.
