### ISSUE TITLE
Manifest generation dies during generation.

### ISSUE THREAD

**Issue by mikewest** [w3c/web-platform-tests#1640]
Running `tools/scripts/manifest.py` gives me:

```
Traceback (most recent call last):
  File "tools/scripts/manifest.py", line 861, in <module>
    update_from_cli(**vars(opts))
  File "tools/scripts/manifest.py", line 819, in update_from_cli
    manifest = load(path)
  File "tools/scripts/manifest.py", line 771, in load
    manifest = Manifest.from_json(json.load(f))
  File "tools/scripts/manifest.py", line 382, in from_json
    self.add(manifest_item)
  File "tools/scripts/manifest.py", line 258, in add
    self._data[item.item_type][item.path].add(item)
  File "tools/scripts/manifest.py", line 127, in path
    return url_to_rel_path(self.url, self.url_base)
  File "tools/scripts/manifest.py", line 64, in url_to_rel_path
    raise ValueError, url
ValueError: 2dcontext/building-paths/canvas_complexshapes_arcto_001-ref.htm
```

Hopping over to `jgraham/reftest_multiple_refs` dies differently:

```
DEBUG:manifest:Opening manifest at /usr/local/google/home/mkwst/Repositories/web-platform-tests/MANIFEST.json
Traceback (most recent call last):
  File "./manifest", line 6, in <module>
    update.main()
  File "/usr/local/google/home/mkwst/Repositories/web-platform-tests/tools/manifest/update.py", line 83, in main
    update_from_cli(**vars(opts))
  File "/usr/local/google/home/mkwst/Repositories/web-platform-tests/tools/manifest/update.py", line 40, in update_from_cli
    m = manifest.load(tests_root, path)
  File "/usr/local/google/home/mkwst/Repositories/web-platform-tests/tools/manifest/manifest.py", line 355, in load
    manifest = Manifest.from_json(tests_root, json.load(f))
  File "/usr/local/google/home/mkwst/Repositories/web-platform-tests/tools/manifest/manifest.py", line 234, in from_json
    source_files=source_files)
  File "/usr/local/google/home/mkwst/Repositories/web-platform-tests/tools/manifest/item.py", line 148, in from_json
    obj["references"],
KeyError: 'references'
```

**Comment by jgraham** [comment]
It sounds like you might have a MANIFEST.json file in an old format. Can you delete that and try again?

**Comment by jgraham** [comment]
I recently landed a PR that will cause the manifest to be automatically regenerated if there's a version mismatch, so this might be fixed now.

**Comment by mikewest** [comment]
Yes, sorry! I killed the file and regenerated, then never came back to this thread. Thanks for the tip!
