### ISSUE TITLE
travis fails on all PR branches while trying to install wptrunner

### ISSUE THREAD

**Issue by sideshowbarker** [w3c/web-platform-tests#4108]
See, e.g., https://travis-ci.org/w3c/web-platform-tests/jobs/171460586#L440

> [31mCommand "/home/travis/virtualenv/python2.7.10/bin/python -u -c "import setuptools, tokenize;**file**='/tmp/pip-WwVrKR-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /tmp/pip-olRcY0-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/travis/virtualenv/python2.7.10/include/site/python2.7/wptrunner" failed with error code 1 in /tmp/pip-WwVrKR-build/[0m

```
DEBUG:check_stability:pip install w3c/wptrunner
[31mCommand "/home/travis/virtualenv/python2.7.10/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-WwVrKR-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-olRcY0-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/travis/virtualenv/python2.7.10/include/site/python2.7/wptrunner" failed with error code 1 in /tmp/pip-WwVrKR-build/[0m
Traceback (most recent call last):
  File "check_stability.py", line 578, in <module>
    retcode = main()
  File "check_stability.py", line 516, in main
    install_wptrunner()
  File "check_stability.py", line 326, in install_wptrunner
    call("pip", "install", os.path.join("w3c", "wptrunner"))
  File "check_stability.py", line 234, in call
    return subprocess.check_output(args)
  File "/opt/python/2.7.10/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '('pip', 'install', 'w3c/wptrunner')' returned non-zero exit status 1
```

**Comment by sideshowbarker** [comment]
cause:

```
    error: Error: setup script specifies an absolute path:
    
        /tmp/pip-Gf2A5k-build/requirements_chrome.txt
    
    setup() arguments must *always* be /-separated paths relative to the
    setup.py directory, *never* absolute paths.
```

https://s3.amazonaws.com/archive.travis-ci.org/jobs/171579264/log.txt

**Comment by sideshowbarker** [comment]
Maybe due to a `setuptools` version change? See http://stackoverflow.com/questions/18085571/pip-install-error-setup-script-specifies-an-absolute-path

**Comment by sideshowbarker** [comment]
This problem is no longer occurring.
