### ISSUE TITLE
Empty aliases config breaks ./serve, possibly breaks w3c-test.org

### ISSUE THREAD

**Issue by domenic** [w3c/web-platform-tests#4161]
@tkent-google's commit 39b65f63fef7d58ef5fbde0ef5f9a64b23e86992 makes it impossible to run `./serve` on a fresh checkout. I get the error

```
$ ./serve
DEBUG:web-platform-tests:Going to use port 50780
Traceback (most recent call last):
  File "./serve", line 5, in <module>
    serve.main()
  File "C:\Users\Domenic\Dropbox\GitHub\w3c\web-platform-tests\serve.py", line 12, in main
    serve.main()
  File "C:\Users\Domenic\Dropbox\GitHub\w3c\web-platform-tests\tools\serve\serve.py", line 604, in main
    config_, servers = start(config, ssl_env, build_routes(config["aliases"]), **kwargs)
  File "C:\Users\Domenic\Dropbox\GitHub\w3c\web-platform-tests\tools\serve\serve.py", line 165, in build_routes
    for url, directory in aliases.items():
AttributeError: 'list' object has no attribute 'items'
```

This might also be why w3c-test.org is down.

**Comment by jgraham** [comment]
I just merged the fix for that, and updated wpt-tools in master. It works for me locally at least.
