### ISSUE TITLE
gaierror: [Errno -2] Name or service not known

### ISSUE THREAD

**Issue by longgehaohaoha** [w3c/web-platform-tests#4368]
after me download the codes, and run git submodule update --init --recursive, and run ./serve， some error occus, 

Process ServerDictManager-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 554, in _run_server
    server = cls._Server(registry, address, authkey, serializer)
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 162, in __init__
    self.listener = Listener(address=address, backlog=16)
  File "/usr/lib/python2.7/multiprocessing/connection.py", line 132, in __init__
    self._listener = SocketListener(address, family, backlog)
  File "/usr/lib/python2.7/multiprocessing/connection.py", line 255, in __init__
    self._socket.bind(address)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
gaierror: [Errno -2] Name or service not known
Traceback (most recent call last):
  File "./serve", line 5, in <module>
    serve.main()
  File "/data/web-platform-tests/serve.py", line 12, in main
    serve.main()
  File "/data/web-platform-tests/tools/serve/serve.py", line 604, in main
    with stash.StashServer((config["host"], get_port()), authkey=str(uuid.uuid4())):
  File "/data/web-platform-tests/tools/wptserve/wptserve/stash.py", line 29, in __enter__
    self.manager, self.address, self.authkey = start_server(self.address, self.authkey)
  File "/data/web-platform-tests/tools/wptserve/wptserve/stash.py", line 51, in start_server
    manager.start()
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 532, in start
    self._address = reader.recv()
EOFError

so, how can I do? thanks

**Comment by agouaillard** [comment]
I'm hitting the same problem. Did you find a solution?

**Comment by agouaillard** [comment]
Solved it in my case. The error message indicate that the requested address / host could not be found. By default it is looking at the address in config.json, which by default is "web-platform.test". I had introduced a typo in my /etc/hosts file, resulting in that address not being defined, which in turn triggered the (cryptic) error.

**Comment by youennf** [comment]
First-time WPT users usually expect the WPT server to run directly without doing anything than launching the serve script. For some users, it is annoying to change /etc/hosts.

If we were using localhost instead of web-platform.test, the server script would work directly in many configurations without any change. This would be more user friendly.

Changing /etc/hosts would only be required for a limited set of tests/limited set of users.

**Comment by agouaillard** [comment]
hi youenn. I'm not exactly first time user, I have been maintaining the media stream and webrtc tests for two years now. However, i did not have to touch the installation for a long time. I configured a new computer last night and an extra "i" was included (you know .... VI users ...). 

I do agree with you though. The first time, I had a lot of very annoying, and confusing for a first timer, problems related to /etc/hosts.

**Comment by bobholt** [comment]
With no response from the original poster, I'm going to close this as "solved by fixing `/etc/hosts`"

We can open a new issue to discuss whether requiring all users to change `/etc/hosts` is a good idea, if that's something we want to pursue.
