### ISSUE TITLE
Stability checker doesn't handle TIMEOUT

### ISSUE THREAD

**Issue by gsnedders** [w3c/web-platform-tests#4985]
see, e.g., https://travis-ci.org/w3c/web-platform-tests/jobs/204278553

```
Traceback (most recent call last):
  File "check_stability.py", line 810, in <module>
    retcode = main()
  File "check_stability.py", line 792, in main
    results, inconsistent = process_results(log, args.iterations)
  File "check_stability.py", line 560, in process_results
    reader.handle_log(reader.read(log), handler)
  File "/home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages/mozlog/reader.py", line 77, in handle_log
    handler(item)
  File "/home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages/mozlog/reader.py", line 71, in __call__
    return handler(data)
  File "check_stability.py", line 522, in test_status
    subtest["status"][data["status"]] += 1
KeyError: u'TIMEOUT'
```

cc/ @bobholt @jgraham @sideshowbarker

**Comment by jugglinmike** [comment]
I'm pretty sure this is a result of a bug in my work introduced via gh-4916. I'll fix it presently
