### ISSUE TITLE
./wptrun configparser dependency

### ISSUE THREAD

**Issue by jeffcarp** [w3c/web-platform-tests#5912]
The new wptrun tool is awesome! I'm not sure if my environment wasn't configured correctly, but I initially got this message and needed to `pip install --user configparser` to fix the problem.

```
./wptrun chrome battery-status                                                                                                                      
Traceback (most recent call last):
  File "./wptrun", line 3, in <module>
    from tools import wptrun
  File "/usr/local/buildtools/current/sitecustomize/sitecustomize.py", line 152, in SetupPathsAndImport
    return real_import(name, globals, locals, fromlist, level)
  File "/usr/local/google/home/jeffcarp/gh/w3c/web-platform-tests/tools/wptrun.py", line 10, in <module>
    from browserutils import browser, utils, virtualenv
  File "/usr/local/google/home/jeffcarp/gh/w3c/web-platform-tests/tools/browserutils/browser.py", line 6, in <module>
    from configparser import RawConfigParser
ImportError: No module named configparser
```

**Comment by gsnedders** [comment]
What Python version are you on? It's in the standard library, and has been since 2.3. What's `sys.path`? What's your `sitecustomize` module doing?

**Comment by jeffcarp** [comment]
Can repro on a Debian VM with Python 2.7.9

```
 jeffcarp@instance-1:/tmp/wpt$ python --version
Python 2.7.9
 jeffcarp@instance-1:/tmp/wpt$ ./wptrun chrome battery-status
Traceback (most recent call last):
  File "./wptrun", line 3, in <module>
    from tools import wptrun
  File "/tmp/wpt/tools/wptrun.py", line 10, in <module>
    from browserutils import browser, utils, virtualenv
  File "/tmp/wpt/tools/browserutils/browser.py", line 6, in <module>
    from configparser import RawConfigParser
ImportError: No module named configparser
```

**Comment by jeffcarp** [comment]
```
>>> sys.path
['', '/home/jeffcarp/gh/w3c/web-platform-tests/tools/wptrunner', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/home/jeffcarp/.local/lib/python2.7/site-packages', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages']
>>> import sitecustomize
>>> sitecustomize
<module 'sitecustomize' from '/usr/lib/python2.7/sitecustomize.pyc'>
```

**Comment by jgraham** [comment]
This got fixed I think.
