### ISSUE TITLE
"No module named wpt" when doing "wpt serve"

### ISSUE THREAD

**Issue by domenic** [w3c/web-platform-tests#6876]
```
Domenic@Revan MINGW64 ~/Dropbox/GitHub/w3c/web-platform-tests (replacement-enabled)
$ ./wpt serve
DEBUG:web-platform-tests:Going to use port 53118
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python27\lib\multiprocessing\forking.py", line 380, in main
    prepare(preparation_data)
  File "C:\Python27\lib\multiprocessing\forking.py", line 503, in prepare
    file, path_name, etc = imp.find_module(main_name, dirs)
ImportError: No module named wpt
Traceback (most recent call last):
  File "./wpt", line 5, in <module>
    wpt.main()
  File "C:\Users\Domenic\Dropbox\GitHub\w3c\web-platform-tests\tools\wpt\wpt.py", line 129, in main
    rv = script(*args, **kwargs)
  File "C:\Users\Domenic\Dropbox\GitHub\w3c\web-platform-tests\tools\serve\serve.py", line 782, in run
    with stash.StashServer(stash_address, authkey=str(uuid.uuid4())):
  File "C:\Users\Domenic\Dropbox\GitHub\w3c\web-platform-tests\tools\wptserve\wptserve\stash.py", line 29, in __enter__
    self.manager, self.address, self.authkey = start_server(self.address, self.authkey)
  File "C:\Users\Domenic\Dropbox\GitHub\w3c\web-platform-tests\tools\wptserve\wptserve\stash.py", line 51, in start_server
    manager.start()
  File "C:\Python27\lib\multiprocessing\managers.py", line 528, in start
    self._address = reader.recv()
EOFError
```

Any ideas? I'm on Windows...

**Comment by domenic** [comment]
I was advised to try a different, undocumented command, but it didn't work either:

```
Domenic@Revan MINGW64 ~/Dropbox/GitHub/w3c/web-platform-tests (replacement-enabled)
$ python tools/wpt/wpt.py serve
Traceback (most recent call last):
  File "tools/wpt/wpt.py", line 6, in <module>
    from tools import localpaths
ImportError: No module named tools
```

**Comment by Hexcles** [comment]
Is this perhaps a Windows/MinGW issue? Do we actually support MinGW? Could you try following this [note](https://github.com/w3c/web-platform-tests#windows-notes) instead?

**Comment by domenic** [comment]
This was cmd.exe. I don't know what mingw is.

**Comment by bobholt** [comment]
@domenic Did @Hexcles note resolve this for you, or is it still an issue?

**Comment by domenic** [comment]
I believe this was fixed separately; @Hexcles's note did not help, but these days it mostly works.

The remaining issue before this can be considered closed, I think, is fixing https://github.com/w3c/web-platform-tests#running-tests-manually to include the Windows version of the command. Currently a later section has an "On Windows" note, but if you're only reading that section, you're in trouble. I would also appreciate a full windows command like, like there is for *nix, not just some prose advising you that the prominent command line is wrong.

**Comment by domenic** [comment]
https://github.com/w3c/web-platform-tests/commit/ef68c32c4958fbac1a63db249db23d7b6e5c6ca6 fixed the remaining documentation issue.
