### ISSUE TITLE
Error running `wpt run`

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/web-platform-tests#7535]
when I run `wpt run`, it aborts with: 

```bash
Traceback (most recent call last):
  File "./wpt", line 5, in <module>
    wpt.main()
  File "/Users/marcos/temp/web-platform-tests/tools/wpt/wpt.py", line 108, in main
    venv = setup_virtualenv(main_args.venv, props)
  File "/Users/marcos/temp/web-platform-tests/tools/wpt/wpt.py", line 83, in setup_virtualenv
    venv.start()
  File "/Users/marcos/temp/web-platform-tests/tools/wpt/virtualenv.py", line 46, in start
    self.activate()
  File "/Users/marcos/temp/web-platform-tests/tools/wpt/virtualenv.py", line 41, in activate
    execfile(path, {"__file__": path})
IOError: [Errno 2] No such file or directory: '/Users/marcos/temp/web-platform-tests/_venv/bin/activate_this.py'
```

And indeed that file is actually at "_venv_Darwin/bin/activate_this.py" instead? 

`wpt serve` works fine tho.

**Comment by marcoscaceres** [comment]
Same error message. Is there some way to get it to rebuild?

**Comment by marcoscaceres** [comment]
Actually, if I delete both it seems to work :)

**Comment by sideshowbarker** [comment]
> Actually, if I delete both it seems to work :)

Super :smile: (The docs really should be updated with a prominent note about this…)
