### ISSUE TITLE
Build errors after no-op file change.

### ISSUE THREAD

**Issue by andypaicu** [w3c/web-platform-tests#7638]
Hello, 

It seems that adding a simple comment to content-security-policy/support/checkReport.sub.js causes the build to fail on all browsers.

Here's a PR where I've tested this: https://github.com/w3c/web-platform-tests/pull/7636

This blocks this PR: https://github.com/w3c/web-platform-tests/pull/6985 as well as (I suspect) an older PR (https://github.com/w3c/web-platform-tests/pull/6467) of mine.

I suspect the file change triggers travis to run a suite of tests that get skipped otherwise and that this has been happening for a while. Unfortunately I don't even know where to begin with investigating this.

Regards,
Andy

**Comment by gsnedders** [comment]
That seemed to fail because of the build running for longer than the maximum time. We don't seem to output the list of tests to run anywhere any more (?!) which doesn't help.

We do have, among other things in the log:

```
Traceback (most recent call last):
  File "/home/travis/build/w3c/web-platform-tests/tools/wptserve/wptserve/handlers.py", line 253, in __call__
    rv = self.func(request, response)
  File "/home/travis/build/w3c/web-platform-tests/content-security-policy/support/report.py", line 33, in main
    request.server.stash.put(key=key, value=report)
  File "/home/travis/build/w3c/web-platform-tests/tools/wptserve/wptserve/stash.py", line 121, in put
    (internal_key, self.data[str(internal_key)], value))
  File "<string>", line 2, in __getitem__
  File "/opt/python/2.7.13/lib/python2.7/multiprocessing/managers.py", line 774, in _callmethod
    raise convert_to_error(kind, result)
KeyError: "('/content-security-policy/support/report.py', '44a6cee7-4155-476e-9855-bd8eb28fbabe')"
```

**Comment by bobholt** [comment]
There are also a few like this:

```
Traceback (most recent call last):

  File "/home/travis/build/w3c/web-platform-tests/tools/wptserve/wptserve/handlers.py", line 253, in __call__

    rv = self.func(request, response)

  File "/home/travis/build/w3c/web-platform-tests/content-security-policy/support/report.py", line 14, in main

    value = request.server.stash.take(key=key)

  File "/home/travis/build/w3c/web-platform-tests/tools/wptserve/wptserve/stash.py", line 131, in take

    internal_key = self._wrap_key(key, path)

  File "/home/travis/build/w3c/web-platform-tests/tools/wptserve/wptserve/stash.py", line 106, in _wrap_key

    return (str(path), str(uuid.UUID(key)))

  File "/opt/python/2.7.13/lib/python2.7/uuid.py", line 136, in __init__

    raise ValueError('badly formed hexadecimal UUID string')

ValueError: badly formed hexadecimal UUID string
```

Most of the errors are as gsnedders notes above, so it appears that however `/content-security-policy/support/report.py` was working before no longer works. Whether this was due to a change in wptrunner and whether that should be fixed (due to a regression) or the CSP test support files need to be changed (due to a regression there or a well-reasoned change in wptrunner behavior), I can't say yet.

**Comment by andypaicu** [comment]
The timeout seems to be the problem, the errors are more of a red herring and easily fixed, I've updated the PR https://github.com/w3c/web-platform-tests/pull/7636 with a fix for them. The build still times out unfortunately.

I'm more curious to know what tests are triggered that cause the build to timeout when we modify these files.

**Comment by andypaicu** [comment]
...or is it just the fact that it runs all csp tests and that just simply takes too long?

**Comment by jgraham** [comment]
From the log:

```
INFO:/home/travis/build/w3c/web-platform-tests/tools/ci/check_stability:Using binary /home/travis/build/w3c/web-platform-tests/_venv/firefox/firefox

DEBUG:/home/travis/build/w3c/web-platform-tests/tools/ci/check_stability:Affected tests:

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib/image-allowed.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib-2/stylenonce-allowed.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib/worker-function-function-blocked.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/generic/generic-0_8_1.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib-2/form-action-src-get-allowed.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/script-src/script-src-1_2.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib-2/form-action-src-redirect-blocked.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib/inline-style-allowed-while-cloning-objects.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib/eval-blocked-and-sends-report.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib/image-blocked.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/media-src/media-src-blocked.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib-2/plugintypes-notype-url.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib/object-src-url-allowed.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib/duplicate-directive.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib/connect-src-xmlhttprequest-allowed.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/media-src/media-src-7_2.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib/self-doesnt-match-blob.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib/style-allowed.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib-2/form-action-src-blocked.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib/connect-src-beacon-allowed.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib-2/plugintypes-nourl-blocked.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib-2/securitypolicyviolation-block-image.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/generic/generic-0_2_3.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib-2/scripthash-unicode-normalization.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/child-src/child-src-allowed.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib/worker-eval-blocked.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/generic/generic-0_10.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/generic/generic-0_10_1.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/script-src/script-src-report-only-policy-works-with-hash-policy.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib/injected-inline-script-blocked.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/script-src/script-src-report-only-policy-works-with-external-hash-policy.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/child-src/child-src-blocked.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib/inline-style-attribute-allowed.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/media-src/media-src-7_3_2.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib/worker-connect-src-blocked.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib/style-blocked.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib/report-cross-origin-no-cookies.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib/connect-src-eventsource-allowed.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib/star-doesnt-match-blob.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib/frame-src-blocked.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib/connect-src-eventsource-redirect-to-blocked.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib-2/form-action-src-allowed.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/child-src/child-src-cross-origin-load.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/navigation/javascript-url-navigation-inherits-csp.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib-2/scriptnonce-redirect.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib-2/form-action-src-default-ignored.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/generic/no-default-src.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/script-src/script-src-multiple-policies-one-using-hashing-algorithms.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib/source-list-parsing-paths-03.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/script-src/script-src-1_3.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/generic/generic-0_2.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/style-src/style-src-multiple-policies-multiple-hashing-algorithms.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/svg/svg-inline.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib/report-uri-from-javascript.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib/function-constructor-allowed.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib-2/form-action-src-javascript-blocked.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib/connect-src-beacon-redirect-to-blocked.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/media-src/media-src-7_1_2.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib-2/scripthash-basic-blocked.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib-2/scripthash-default-src.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib-2/plugintypes-nourl-allowed.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/generic/generic-0_2_2.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib/inline-style-blocked.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib-2/scripthash-ignore-unsafeinline.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib/inline-style-attribute-on-html.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/media-src/media-src-7_1.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/child-src/child-src-conflicting-frame-src.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib-2/scriptnonce-basic-blocked.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/script-src/script-src-1_4_2.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/generic/generic-0_9.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib/combine-header-and-meta-policies.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib/eval-allowed.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib-2/securitypolicyviolation-block-cross-origin-image-from-script.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib/default-src-inline-allowed.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/child-src/child-src-about-blank-allowed-by-scheme.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib/inline-style-allowed.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib-2/stylenonce-blocked.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib/injected-inline-style-allowed.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib-2/base-uri-deny.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib/media-src-track-block.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib/frame-src-cross-origin-load.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib-2/securitypolicyviolation-block-cross-origin-image.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib/connect-src-beacon-blocked.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib-2/plugintypes-mismatched-data.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/media-src/media-src-redir-bug.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/child-src/child-src-redirect-blocked.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/script-src/script-src-1_2_1.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib/connect-src-websocket-allowed.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib-2/securitypolicyviolation-block-image-from-script.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib/filesystem-urls-match-filesystem.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib-2/scriptnonce-allowed.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/script-src/script-src-1_4.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib/worker-importscripts-blocked.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib/shared-worker-connect-src-blocked.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib-2/stylehash-allowed.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib-2/form-action-src-get-blocked.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib/shared-worker-connect-src-allowed.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/object-src/object-src-2_2.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib-2/scriptnonce-and-scripthash.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/media-src/media-src-7_2_2.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib/object-src-no-url-blocked.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib-2/plugintypes-mismatched-url.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/script-src/script-src-1_4_1.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib/report-disallowed-from-meta.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/child-src/child-src-about-blank-allowed-by-default.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib/frame-src-allowed.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib/default-src-inline-blocked.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib-2/plugintypes-notype-data.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib/connect-src-websocket-blocked.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/script-src/javascript-window-open-blocked.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib-2/meta-outside-head.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib/injected-inline-style-blocked.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib/worker-from-guid.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib/report-same-origin-with-cookies.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib/report-uri-from-inline-javascript.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/script-src/script-src-1_10.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib/script-src-overrides-default-src.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/generic/generic-0_1-img-src.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib/object-src-url-blocked.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib/worker-connect-src-allowed.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/script-src/script-src-1_1.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib/connect-src-xmlhttprequest-blocked.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib/image-full-host-wildcard-allowed.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib/function-constructor-blocked.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/generic/generic-0_8.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib-2/scripthash-allowed.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib/connect-src-eventsource-blocked.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib/worker-set-timeout-blocked.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib/object-in-svg-foreignobject.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib-2/base-uri-allow.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/script-src/script-src-multiple-policies-multiple-hashing-algorithms.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib/srcdoc-doesnt-bypass-script-src.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib/frame-src-about-blank-allowed-by-default.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib/blob-urls-do-not-match-self.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/media-src/media-src-7_3.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/script-src/script-src-1_10_1.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib-2/stylehash-basic-blocked.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib/filesystem-urls-do-not-match-self.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib/worker-script-src.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib-2/scriptnonce-ignore-unsafeinline.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/object-src/object-src-2_1.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib/eval-blocked.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib/blob-urls-match-blob.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib/inline-style-attribute-blocked.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/generic/generic-0_1-script-src.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib/connect-src-xmlhttprequest-redirect-to-blocked.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib-2/stylehash-default-src.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib/report-blocked-data-uri.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib/object-src-no-url-allowed.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib/injected-inline-script-allowed.sub.html

 * /home/travis/build/w3c/web-platform-tests/content-security-policy/blink-contrib/frame-src-about-blank-allowed-by-scheme.sub.html
```

This is just failing because it affects too many tests to run them all 10x in the allowed time.

**Comment by andypaicu** [comment]
Ok, I'll have a look at them, I suspect most of those tests don't need to use checkreport at all and could just make do with violation event checks.

**Comment by JKereliuk** [comment]
@andypaicu Is there an update on this?

**Comment by andypaicu** [comment]
Yes, I have made a bunch of changes that refactored blink-contrib and blink-contrib-2. I'll be looking at this today to see if it's fixed now.

**Comment by andypaicu** [comment]
The issue should now be fixed
