### ISSUE TITLE
Outdated virtualenv causes obscure errors

### ISSUE THREAD

**Issue by kereliuk** [w3c/web-platform-tests#8954]
When I run

`./wpt run firefox webrtc --install-browser --yes --certutil-binary=certutil --setpref media.navigator.streams.fake=true --log-mach=- --log-wptreport /home/ubuntu/wptdbuild/wptd-6c663c53af-firefox-57.0-linux-report.log --install-fonts`

I get a TypeError when it tries to do some logging set up.
```
0:00.00 LOG: MainThread INFO Installing browser
Using webdriver binary /home/ubuntu/web-platform-tests/_venv/bin/geckodriver
Downloading gecko prefs
 0:16.16 LOG: MainThread INFO Updating test manifest /home/ubuntu/web-platform-tests/MANIFEST.json
 0:16.16 LOG: Thread-Log INFO STDOUT: INFO:manifest:Skipping manifest download because existing file is recent
 0:19.34 LOG: Thread-Log INFO STDOUT: INFO:manifest:Updating manifest
 0:27.24 LOG: Thread-Log INFO STDOUT: DEBUG:manifest:Opening manifest at /home/ubuntu/web-platform-tests/MANIFEST.json
 0:31.57 LOG: MainThread INFO Using 1 client processes
 0:31.71 LOG: MainThread INFO Closing logging queue
 0:31.71 LOG: MainThread INFO queue closed
Traceback (most recent call last):
  File "./wpt", line 5, in <module>
    wpt.main()
  File "/home/ubuntu/web-platform-tests/tools/wpt/wpt.py", line 132, in main
    rv = script(*args, **kwargs)
  File "/home/ubuntu/web-platform-tests/tools/wpt/run.py", line 393, in run
    rv = run_single(venv, **kwargs) > 0
  File "/home/ubuntu/web-platform-tests/tools/wpt/run.py", line 400, in run_single
    return wptrunner.start(**kwargs)
  File "/home/ubuntu/web-platform-tests/tools/wptrunner/wptrunner/wptrunner.py", line 294, in start
    return not run_tests(**kwargs)
  File "/home/ubuntu/web-platform-tests/tools/wptrunner/wptrunner/wptrunner.py", line 204, in run_tests
    logger.suite_start(test_loader.test_ids, name='web-platform-test', run_info=run_info)
  File "/home/ubuntu/web-platform-tests/_venv/lib/python2.7/site-packages/mozlog/logtypes.py", line 49, in inner
    data = converter.convert(*args, **kwargs)
  File "/home/ubuntu/web-platform-tests/_venv/lib/python2.7/site-packages/mozlog/logtypes.py", line 94, in convert
    raise TypeError("Unrecognised argument %s" % key)
TypeError: Unrecognised argument name
```

**Comment by jgraham** [comment]
You need to update mozlog. Either delete the `_venv` directory or activate the virtualenv and run `pip install -U mozlog`. There must be some way to make this better.

**Comment by gsnedders** [comment]
@foolip I wonder if this should be higher priority (roadmap?), as it's potentially an issue more generally when dependencies get updated?

**Comment by domfarolino** [comment]
Just ran into the same thing with `./wpt run chrome console/...`, fixed by deleting _venv and running `./wpt run chrome console/...` which prompted me to redownload/install the appropriate webdriver

**Comment by gsnedders** [comment]
I don't understand how this is failing, we always install the requirements file, so it should work. Unless the requirements file hasn't got updated when we've moved to requiring more up-to-date versions?
