### ISSUE TITLE
{{domains[non-existent]}} doesn't work

### ISSUE THREAD

**Issue by gsnedders** [w3c/web-platform-tests#9232]
```
Traceback (most recent call last):
  File "/Users/gsnedders/Documents/other-projects/wpt/web-platform-tests/tools/wptserve/wptserve/server.py", line 255, in handle_one_request
    handler(request, response)
  File "/Users/gsnedders/Documents/other-projects/wpt/web-platform-tests/tools/wptserve/wptserve/handlers.py", line 150, in __call__
    response = wrap_pipeline(path, request, response)
  File "/Users/gsnedders/Documents/other-projects/wpt/web-platform-tests/tools/wptserve/wptserve/handlers.py", line 116, in wrap_pipeline
    response = pipeline(request, response)
  File "/Users/gsnedders/Documents/other-projects/wpt/web-platform-tests/tools/wptserve/wptserve/pipes.py", line 34, in __call__
    response = func(request, response, *args)
  File "/Users/gsnedders/Documents/other-projects/wpt/web-platform-tests/tools/wptserve/wptserve/pipes.py", line 127, in inner
    return f(request, response, *arg_values)
  File "/Users/gsnedders/Documents/other-projects/wpt/web-platform-tests/tools/wptserve/wptserve/pipes.py", line 363, in sub
    new_content = template(request, content, escape_type=escape_type)
  File "/Users/gsnedders/Documents/other-projects/wpt/web-platform-tests/tools/wptserve/wptserve/pipes.py", line 432, in template
    new_content = template_regexp.sub(config_replacement, content)
  File "/Users/gsnedders/Documents/other-projects/wpt/web-platform-tests/tools/wptserve/wptserve/pipes.py", line 417, in config_replacement
    value = value[item[1]]
KeyError: u'non-existent'
```

Fundamentally, this is because `config.domains` is a dict that only includes domains that actually exist. It means non-existent can only be referred to as `non-existent.{{host}}`.

**Comment by gsnedders** [comment]
Fixed by #8614.
