### ISSUE TITLE
Travis CI is failing on Chrome, Safari, and Edge

### ISSUE THREAD

**Issue by npm1** [w3c/web-platform-tests#9520]
Most Pull Request builds are failing on 3 of the 4 Allowed-Failures and they have been failing for a long time: https://travis-ci.org/w3c/web-platform-tests/pull_requests

The builds fail due to incorrect runner script, not due to the tests themselves. This is bad because we cannot check results for browsers different from Firefox, nor detect flaky results.

Sample error message:

```
Traceback (most recent call last):
  File "./wpt", line 5, in <module>
    wpt.main()
  File "/home/travis/build/w3c/web-platform-tests/tools/wpt/wpt.py", line 132, in main
    rv = script(*args, **kwargs)
  File "/home/travis/build/w3c/web-platform-tests/tools/ci/check_stability.py", line 360, in run
    iterations, results, inconsistent = run(venv, wpt_logger, **wpt_kwargs)
  File "/home/travis/build/w3c/web-platform-tests/tools/wpt/stability.py", line 188, in run
    wptrunner.run_tests(**kwargs)
  File "/home/travis/build/w3c/web-platform-tests/tools/wptrunner/wptrunner/wptrunner.py", line 145, in run_tests
    env_extras = get_env_extras(**kwargs)
  File "/home/travis/build/w3c/web-platform-tests/tools/wptrunner/wptrunner/browsers/sauce.py", line 112, in env_extras
    return [SauceConnect(**kwargs)]
  File "/home/travis/build/w3c/web-platform-tests/tools/wptrunner/wptrunner/browsers/sauce.py", line 130, in __init__
    self.config = kwargs["config"]
KeyError: 'config'
```

**Comment by foolip** [comment]
@gsnedders, I'm going away until Tuesday, could you see if you know what this is, and what should be done about it?

**Comment by gsnedders** [comment]
(This is a regression from #8614, which landed on the 9th, five days ago.)

**Comment by gsnedders** [comment]
With those fixed this should be working.
