### ISSUE TITLE
./wpt run appears to be broken on mac

### ISSUE THREAD

**Issue by kereliuk** [w3c/web-platform-tests#9578]
Seems to be some issue with the logger

Traceback (most recent call last):
  File "./wpt", line 5, in <module>
    wpt.main()
  File "/Users/kereliuk/web-platform-tests/tools/wpt/wpt.py", line 132, in main
    rv = script(*args, **kwargs)
  File "/Users/kereliuk/web-platform-tests/tools/wpt/run.py", line 419, in run
    rv = run_single(venv, **kwargs) > 0
  File "/Users/kereliuk/web-platform-tests/tools/wpt/run.py", line 426, in run_single
    return wptrunner.start(**kwargs)
  File "/Users/kereliuk/web-platform-tests/tools/wptrunner/wptrunner/wptrunner.py", line 295, in start
    return not run_tests(**kwargs)
  File "/Users/kereliuk/web-platform-tests/tools/wptrunner/wptrunner/wptrunner.py", line 204, in run_tests
    logger.suite_start(test_loader.test_ids, name='web-platform-test', run_info=run_info)
  File "/Users/kereliuk/web-platform-tests/_venv/lib/python2.7/site-packages/mozlog/logtypes.py", line 49, in inner
    data = converter.convert(*args, **kwargs)
  File "/Users/kereliuk/web-platform-tests/_venv/lib/python2.7/site-packages/mozlog/logtypes.py", line 94, in convert
    raise TypeError("Unrecognised argument %s" % key)
TypeError: Unrecognised argument name

**Comment by kereliuk** [comment]
another instance of #9546 ?

**Comment by gsnedders** [comment]
No, another instance of #8954
