### ISSUE TITLE
wptrunner_infrastructure test job getting no results from Chrome but passing

### ISSUE THREAD

**Issue by gsnedders** [w3c/web-platform-tests#9979]
See e.g. https://travis-ci.org/w3c/web-platform-tests/jobs/352408702

From end:

```
 0:28.80 pid:8263 Full command: /home/travis/build/w3c/web-platform-tests/_venv/bin/chromedriver --port=4445 --url-base=/
pid:8263 Starting ChromeDriver 2.36.540471 (9c759b81a907e70363c6312294d30b6ccccc2752) on port 4445
 0:28.80 pid:8263 Only local connections are allowed.
 0:29.30 INFO Starting runner
 0:29.53 WARNING Connecting to Selenium failed:
Traceback (most recent call last):
  File "/home/travis/build/w3c/web-platform-tests/tools/wptrunner/wptrunner/executors/executorselenium.py", line 53, in setup
    desired_capabilities=self.capabilities)
  File "/home/travis/build/w3c/web-platform-tests/_venv/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 154, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/home/travis/build/w3c/web-platform-tests/_venv/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 243, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/travis/build/w3c/web-platform-tests/_venv/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "/home/travis/build/w3c/web-platform-tests/_venv/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
SessionNotCreatedException: Message: session not created exception: Chrome version must be >= 63.0.3239.0
  (Driver info: chromedriver=2.36.540471 (9c759b81a907e70363c6312294d30b6ccccc2752),platform=Linux 4.4.0-101-generic x86_64)
 0:29.54 WARNING Failed to connect to Selenium
 0:29.56 WARNING u'runner_teardown': ()
 0:29.56 ERROR Max restarts exceeded
 0:29.56 INFO Got 0 unexpected results
 0:29.56 SUITE_END

web-platform-test
~~~~~~~~~~~~~~~~~
Ran 0 checks ()
Expected results: 0
OK
```

We install the `google-chrome-unstable` package at version 66.0.3359.22-1, which I believe to be >= 63.0.3239.0.

It's also sad that this test job passes when we get zero results.

**Comment by gsnedders** [comment]
cc/ @jgraham @foolip @kereliuk

**Comment by Hexcles** [comment]
Yes I also noticed this when filing #9932; this is a blocking issue for disallowing Chrome failures (i.e. #9932).

I'll look into it this week.
